.TH FAST-VM 8 "fast-vm-net-cleanup 1.4 (2018-06-17)" "fast-vm" "fast-vm-net-cleanup" \" -*- nroff -*-
.SH NAME
fast-vm-net-cleanup \(em script for removing staled DHCP leases from fast-vm libvirt network
.SH SYNOPSIS
.B fast-vm-net-cleanup
.br

.SH DESCRIPTION
fast-vm-net-cleanup checks currently removes the DHCP reservations in fast-vm libvirt network
for the VMs that doesn't exists anymore.

.SH SEE ALSO
.BR fast-vm (8)
