.TH FAST-VM 8 "fast-vm 1.2 (2017-11-14)" "fast-vm" "fast-vm" \" -*- nroff -*-
.SH NAME
fast-vm list \(em shows the list of VMs recognized by fast-vm
.SH SYNOPSIS

.B fast-vm
.B list
.RB [ all | active | inactive
.RB [ short ]]

.SH DESCRIPTION
Without any additional parameters list is shortcut for 'fast-vm list all'.
The 'all' keyword represents all running and inactive VMs that fast-vm can recognize.
Alternative keyword available are 'active' and 'inactive' that shows running and inactive
VMs repsectivelly.

For programatical use there is additional parameter called 'short' which will cause the output
to only print the matching VM numbers - one number per line.

.SH OUTPUT description
Below is explanation of columns printed by 'list' action.

.TP
.B VM#
VmNumber - VM number as identified by fast-vm

.TP
.B Image name
Name of the image, based on which this VM was created.

.TP
.B Status
The VMs status as reported by libvirt.

.TP
.B Profile_name
If the VMs was created using the profile then here is the name of profile. If no profile was used, then text '---' is present and VM is based only on the Image name. Profiles can define a special behaviour for VM creation and deletion but will always reuse the same Image.

.TP
.B Size ( %used )
Size of the VMs primary drive in GB and the percentage usage as reported by LVM. This is space that was used by VM and never marked as free. To save space you can try to use 'fstrim' inside of VM to mark empty space in way that LVM thin pool can reuse it.

.TP
.B Activity
Whole number of days since the last action done to listed VM. This value helps to determine which VMs were not used for extended period of time and might be cosidered for removal. The following list of actions affects this value: start, stop, ssh, console, resize, info.

.TP
.B Notes
Shows the name of user which created this VM and is considered as VM owner along with free for text that can be changed using 'fast-vm edit_note' command.

.SH EXAMPLE OUTPUT

VM# Image name   Status    Profile_name Size( %used )  Activity  Notes
 29 centos-7.4   shut off  ---            6g( 17.23%)   53d ago  ondrej: machine with CentOS
 43 fedora26     shut off  ---           10g( 18.20%)    6d ago  ondrej: build system
 45 centos-6.9   shut off  c6.9-cluster   6g( 29.90%)  132d ago  ondrej: node 1 with shared storage
 46 centos-6.9   shut off  c6.9-cluster   6g( 27.20%)  132d ago  ondrej: node 2 with shared storage

.SH SEE ALSO
.BR fast-vm (8)
