.TH FAST-VM.CONF 5 "fast-vm 0.9 (2016-10-07)" "fast-vm" "/etc/fast-vm.conf" \" -*- nroff -*-
.SH NAME
.IR /etc/fast-vm.conf " \(em global configuration file for fast-vm"

.SH DESCRIPTION
.RB "This manual page describes the format of the " fast-vm " (8) configuration file."

the /etc/fast-vm.conf must exist to fast-vm function properly. On first configuration the default 
values are taken from file /usr/share/fast-vm/fast-vm.conf.defaults.

File is loaded as shell script that provides variables to fast-vm script.

Following variables are defined

.TP
.B VM_PREFIX
Prefix for LV disk name and libvirt machine name.

.TP 
.B THINPOOL_VG
Name of Volume Group (VG) on which is the thin LV for fast-vm.

.TP
.B THINPOOL_LV
Name of Thinpool Logical Volume (LV) for fast-vm.

.TP
.B LIBVIRT_NETWORK
Name of the libvirt network and bridge adapter for NAT networking.

.TP
.B SUBNET_NUMBER
The XX in the 192.168.XX.0/24 libvirt network created by setup.

.TP
.B FASTVM_GROUP
System group which will be allowed access to fast-vm. Users in this group can use fast-vm
and fast-vm will allow access disks to this group (prior to version 0.9 this was a 'libvirt' group).
If you setup this to other group than 'libvirt' you would most probably need to allow RW access for
this groupto libvirt RW socket. typicaly this can be done by changing following two options in
.BR /etc/libvirt/libvirtd.conf ". Changes below disable polkit authentication."
.sp
.BI "unix_sock_group = " "<new_group>"
.sp
.BI "auth_unix_rw =  " "none"

.TP
.B LOG_LEVEL
Defines the minimum priority of messages that will be logged to syslog. Default is 7 (debug = all messages)

.TP
.B DISPLAY_LEVEL
Defines the minimum priority of messages that will be showed when running fast-vm. Default is 7 (debug = all messages)

.TP
.B FASTVM_NOTES_DIR
Directory in which to store notes for VMs taht are shown in 'Notes' column when listing VMs. Defaults to
.BR /var/tmp

.TP
.B FASTVM_OWNER_ONLY_DELETE
Allow only 'root' and VM 'owner' to delete VM. In fast-vm versions =< 0.9 all users able to use fast-vm can delete any fast-vm VM. Default is 
.BR no ". To enable this behaviour set this to " yes .

.SH SEE ALSO
.BR fast-vm (8),
.BR configure-fast-vm (8)
