#!/bin/bash
DEBUG_LOG=/tmp/fast-vm.debug.log
FASTVM_HELPER=/usr/libexec/fast-vm-helper.sh

## terminal colors
c_red=$(tput setaf 1)
c_yellow=$(tput setaf 3)
c_green=$(tput setaf 2)
c_cyan=$(tput setaf 6)
c_normal=$(tput sgr0)
## common outputs
o_err="[${c_red}err${c_normal}]"
o_wrn="[${c_yellow}wrn${c_normal}]"
o_inf="[${c_cyan}inf${c_normal}]"
o_ok="[${c_green}ok${c_normal}]"

#### start common functions
# helper function for loading and checking configuration
check_empty () {
	var_name="$1"
	var_value="$2"
	if [ -z "$var_value" ]; then
                printf "$o_err variable $var_name not declared in global configuration run configure-fast-vm again or fix manually\n"
		exit 2
	fi
}

wait_for_ssh () {
	vm_number="$1"
	printf "$o_inf checking the 192.168.$SUBNET_NUMBER.$vm_number for active SSH connection (ctrl+c to interrupt)\n"
	ssh_ready=$(ssh-keyscan -T 1 "192.168.$SUBNET_NUMBER.$vm_number" 2>/dev/null|egrep '(ssh-|ecdsa-)'|wc -l)
	while [ "$ssh_ready" -eq "0" ];
	do
		printf "."
		ssh_ready=$(ssh-keyscan -T 1 "192.168.$SUBNET_NUMBER.$vm_number" 2>/dev/null|egrep '(ssh-|ecdsa-)'|wc -l)
		sleep 1
	done
	printf "\n$o_inf SSH ready"
}

check_file () {
	file_path="$1"
	file_size=0
	file_local=0
	error_prefix="$2"
	if [ "$curl_ok" -eq 0 ] && [ $(echo $file_path | awk  '{ s=substr($0, 0, 4); print s; }' )  = "http" ]; then
		curl_data=$(curl --head "$file_path" 2>/dev/null)
		curl_httpok=$(echo "$curl_data"|egrep "HTTP.*200 OK"|wc -l)
		if [ "$curl_httpok" -eq "1" ]; then
			file_size=$(echo "$curl_data"|grep "Content-Length:"|awk '{print $2}'|sed 's/[^0-9]*//g')
			printf "$o_inf Detected remote file with size $file_size\n"
		else
			printf "$o_err $error_prefix: error checking remote file on the server, we got following information from server\n%s\n" "$curl_data"
			exit 2
		fi
	else
		if [ -f "$file_path" ]; then
			file_local=1
		else
			printf "$o_err $error_prefix: local file not found\n"
			exit 2
		fi
	fi
}

download_file () {
	file_url="$1"
	tmp_file=$(mktemp)
	printf "$o_inf downloading $file_url\ninto $tmp_file\n" >&2
	curl -o $tmp_file -s "$file_url"
	if [ "$?" -eq 0 ]; then
		echo "$tmp_file"
	else
		printf "$o_err Download failed\n" >&2
		exit 1
	fi
}

usage () {
	part="$1"

	echo ''
	case $part in
		import_image)
			echo "$0 import_image ImageName PathToImage PathToLibvirtXML [PathToHacksFile]"
			;;
		remove_image)
			echo "$0 remove_image ImageName"
			;;
		create)
			echo "$0 create ImageName <base |VmNumber> [PathToLibvirtXML] [PathToHacksFile]"
			;;
		start)
			echo "$0 start VmNumber [console|ssh [/path/to/custom/script]]"
			;;
		stop)
			echo "$0 stop VmNumber [graceful]"
			;;
		console)
			echo "$0 console VmNumber"
			;;
		ssh)
			echo "$0 ssh VmNumber [/path/to/custom/script]"
			;;
		delete)
			echo "$0 delete VmNumber"
			;;
		list)
			echo "$0 list"
			;;
		*)
cat <<EOF
fast-vm <action> <options>

fast-vm import_image ImageName PathToImage PathToLibvirtXML [PathToHacksFile]
fast-vm remove_image ImageName
fast-vm create ImageName <base |VmNumber> [PathToLibvirtXML] [PathToHacksFile]
fast-vm delete VmNumber
fast-vm list
fast-vm start VmNumber [console|ssh [/path/to/custom/script]]
fast-vm stop VmNumber [graceful]
fast-vm console VmNumber
fast-vm ssh VmNumber [/path/to/custom/script]

== fast-vm version 0.5 <ofamera@redhat.com> ==
EOF
			;;
	esac
	exit 1
}

#### end common functions

# first parameter is compulsory
if [ -z "$1" ]; then usage; fi

# check if we are in libvirt group or if we are root
if [ $(id |grep '(libvirt)'|wc -l) -eq 0 ] && [ $(whoami) != "root" ]; then
	printf "$o_err User running fast-vm must be member of group 'libvirt'. You can easily add user to libvirt group using command below\n # usermod -a -G libvirt <user>\n"
	exit 1
fi

# locate and load fast-vm configuration
if [ -f "/etc/fast-vm.conf" ]; then
	# load and verify configuration
	. /etc/fast-vm.conf

	check_empty "VM_PREFIX" "$VM_PREFIX"
	check_empty "LIBVIRT_NETWORK" "$LIBVIRT_NETWORK"
	check_empty "THINPOOL_VG" "$THINPOOL_VG"
	check_empty "THINPOOL_LV" "$THINPOOL_LV"
	check_empty "SUBNET_NUMBER" "$SUBNET_NUMBER"
else
	printf "$o_err no global configuration file /etc/fast-vm.conf not found please run configure-fast-vm as root before using fast-vm\n"
	exit 1
fi

## check if there is curl available so we can fetch images from http/https
which curl >/dev/null 2>&1
curl_ok="$?"
which pv >/dev/null 2>&1
pv_ok="$?"

#### main script
case "$1" in
	import_image)
		image_name="$2"
		if [ -z "$image_name" ]; then printf "$o_err missing image name\n"; usage import_image; fi
		image_path="$3"
		check_file "$image_path" "image file"
		image_path="$file_path"
		image_size="$file_size"
		image_local="$file_local"
		image_extension="${image_path##*.}"
		case "$image_extension" in
			gz)
				decompress_cmd="gunzip -c"
				;;
			xz)
				decompress_cmd="xz -d -c"
				;;
			*)
				printf "$o_err unknown image file extension $image_extension, (supported: xz, gz)\n"
				exit 1
				;;
		esac

		image_xml_path="$4"
		check_file "$image_xml_path" "XML VM definition"
		if [ "$file_local" -eq '0' ]; then
			image_xml_path=$(download_file "$image_xml_path")
		fi

		hack_file="$5"
		if [ ! -z "$hack_file" ]; then
			check_file "$hack_file" "hack file"
			if [ "$file_local" -eq '0' ]; then
				hack_file=$(download_file "$hack_file")
			fi
		fi

		if [ -b "/dev/$THINPOOL_VG/$VM_PREFIX$image_name" ]; then
			printf "$o_err base image for '$image_name' version already exists. To remove image use 'remove_image' parameter\n"
			exit 1

		else
			printf "$o_inf creating LV $VM_PREFIX$image_name ...\n"
			echo "lvcreate" "base" "$image_name" | sudo -n $FASTVM_HELPER
			if [ "$?" != "0" ]; then
				echo "[err] Error creating thin LV for VM image"
				exit 1
			fi
		fi

		printf "$o_inf importing image $image_path into /dev/$THINPOOL_VG/$VM_PREFIX$image_name\n"
		echo "chgrp" "/dev/$THINPOOL_VG/$VM_PREFIX$image_name" | sudo -n $FASTVM_HELPER

		if [ "$image_local" -eq "1" ]; then
			if [ "$pv_ok" -eq '0' ]; then
				$decompress_cmd "$image_path"| pv -s 10G | dd of=/dev/$THINPOOL_VG/$VM_PREFIX$image_name bs=1M conv=sparse >>$DEBUG_LOG 2>&1
				import_exit="$?"
			else
				printf "$o_inf please wait while importing image (to show progress, install 'pv')\n"
				$decompress_cmd "$image_path"| dd of=/dev/$THINPOOL_VG/$VM_PREFIX$image_name bs=1M conv=sparse >>$DEBUG_LOG 2>&1
				import_exit="$?"
			fi
		else
			# import from http(s)
			if [ "$pv_ok" -eq '0' ]; then
				curl -s "$image_path" | pv -N download -c -s "$image_size" | $decompress_cmd | pv -N unpack -c -s 10737418240 | dd of=/dev/$THINPOOL_VG/$VM_PREFIX$image_name bs=1M conv=sparse >>$DEBUG_LOG 2>&1
				import_exit="$?"
			else
				printf "$o_inf please wait while importing image (to show image write progress, install 'pv')\n"
				curl "$image_path" | $decompress_cmd | dd of=/dev/$THINPOOL_VG/$VM_PREFIX$image_name bs=1M conv=sparse 2>>$DEBUG_LOG
				import_exit="$?"
			fi

		fi
		if [ "$import_exit" != "0" ]; then
			printf "$o_err Error copying the image into thin LV\n"
			exit 1
		fi

		# copy the XML configuration file
		if [ ! -d "$HOME/.fast-vm" ]; then 
			mkdir "$HOME/.fast-vm" >>$DEBUG_LOG 2>&1
		fi
		cp "$image_xml_path" "$HOME/.fast-vm/config-${image_name}.xml" >>$DEBUG_LOG 2>&1
		if [ ! -z "$hack_file" ] && [ -f "$hack_file" ]; then
			cp "$hack_file" "$HOME/.fast-vm/hacks-${image_name}.sh" >>$DEBUG_LOG 2>&1
			chmod +x "$HOME/.fast-vm/hacks-${image_name}.sh" >>$DEBUG_LOG 2>&1
		fi

		printf "$o_ok image imported\n"
		;;
	remove_image)
		image_name="$2"
		if [ -z "$image_name" ]; then printf "$o_err missing image name\n"; usage remove_image; fi

		if [ -b "/dev/$THINPOOL_VG/$VM_PREFIX$image_name" ]; then
			printf "$o_inf stopping and undefining the base VM\n"
			virsh --connect qemu:///system destroy $VM_PREFIX$image_name >>$DEBUG_LOG 2>&1
			virsh --connect qemu:///system undefine $VM_PREFIX$image_name >>$DEBUG_LOG 2>&1
			printf "$o_inf removing LV $VM_PREFIX$image_name ...\n"
			echo "lvremove" "/dev/$THINPOOL_VG/$VM_PREFIX$image_name" | sudo -n $FASTVM_HELPER
		else
			printf "$o_err image "$image_name" not found\n"
			usage remove_image
		fi
		;;
	create)
		image_name="$2"
		if [ -z "$image_name" ]; then printf "$o_err missing image name\n"; usage create; fi

		image_xml_path="$4"
		if [ ! -z "$image_xml_path" ]; then
			check_file "$image_xml_path" "alternative XML VM definition"
			if [ "$file_local" -eq '0' ]; then
	                        image_xml_path=$(download_file "$image_xml_path")
	                fi
			printf "$o_inf using alternative xml file $image_xml_path\n"
		else
			if [ ! -f "$HOME/.fast-vm/config-${image_name}.xml" ]; then
				printf "$o_err no VM XML definition for this version. $HOME/.fast-vm/config-${image_name}.xml not found. Import image again or supply alternative xml\n"
				usage create
			fi
			image_xml_path="$HOME/.fast-vm/config-${image_name}.xml"
		fi

		hack_file="$5"
		if [ ! -z "$hack_file" ]; then
			check_file "$hack_file" "alternative hack file"
			if [ "$file_local" -eq '0' ]; then
                                hack_file=$(download_file "$hack_file")
                        fi
			printf "$o_inf using alternative hack file $hack_file\n"
		else
			if [ ! -f "$HOME/.fast-vm/hacks-${image_name}.sh" ]; then
				printf "$o_wrn no default hacks file for this version. $HOME/.fast-vm/hacks-${image_name}.sh not found\n"
			else
				hack_file="$HOME/.fast-vm/hacks-${image_name}.sh"
			fi
		fi

		if [ ! -b "/dev/$THINPOOL_VG/$VM_PREFIX$image_name" ]; then
			printf "$o_err Missing image for this image name.\n/dev/$THINPOOL_VG/$VM_PREFIX$image_name not found.\nFirst import image using 'fast-vm image_import $image_name'\n"
			exit 2
		fi

		vm_number="$3"
		# validate vm_number is a 'number'
		$(echo "$vm_number" | grep -Eq '^[+-]?[0-9]+$')
		if [ "$?" -eq '0' ]
		then
			if [ "$vm_number" -lt 20 ] || [ "$vm_number" -gt 220 ];then
				printf "$o_err VM number out of range (20-220)\n"
				usage create
			fi
		else
			if [ "$vm_number" = "base" ]; then
				printf "$o_inf creating base image VM\n"
			else
				printf "$o_err only numbers from range 20-220 and word 'base' permited here\n"
				usage create
			fi
		fi

		# special case for creating only base image
		if [ "$vm_number" = "base" ]; then
			VM_NAME="$VM_PREFIX$image_name"
			
			tmp_xml=$(mktemp --suffix=.xml)
			sed -e "s/VM_NAME/$VM_PREFIX$image_name/g; s/THINPOOL_VG/$THINPOOL_VG/g; s/LIBVIRT_NETWORK/$LIBVIRT_NETWORK/g;" "$image_xml_path" > $tmp_xml
			virsh --connect qemu:///system define $tmp_xml >>$DEBUG_LOG 2>&1
			if [ ! "$?" -eq '0' ]; then
				printf "$o_err defining base VM failed, doesn't exists alreadry?\n"
				exit 2
			fi

			# source file with hacks and apply them
			if [ ! -z "$hack_file" ]; then
				printf "$o_inf applying hacks from $hack_file\n"
				. $hack_file
				if [ ! "$?" -eq "0" ]; then
					printf "$o_wrn there was issue applying hacks to this machine, check $DEBUG_LOG for more details\n"
				fi
				printf "$o_inf applying hacks finished\n"
			fi

			printf "$o_inf base image VM created, to start this VM use 'virsh --connect qemu:///system start $VM_PREFIX$image_name'. This VM is used for customizing the base image of '$image_name' VMs. All changes you make to this VM would be available in newly created VMs of that version, this will not affect already existing VMs of same version\n"
			exit 0
		fi
		
		## check if the machine doesn't exists already
		vm_disk_test=$(ls /dev/${THINPOOL_VG}/${VM_PREFIX}*-${vm_number} 2>/dev/null|wc -l )
		if [ "$vm_disk_test" -gt 0 ]; then
			printf "$o_err there is already disk for this machine, VM creation aborted\n"
			exit 1
		fi

		## create regular machine
		VM_NAME="$VM_PREFIX$image_name-$vm_number"

		printf "$o_inf defining virtual machine '$VM_PREFIX$image_name-$vm_number' in libvirt\n"
		tmp_xml=$(mktemp --suffix=.xml)
		sed -e "s/VM_NAME/$VM_PREFIX$image_name-$vm_number/g; s/THINPOOL_VG/$THINPOOL_VG/g; s/LIBVIRT_NETWORK/$LIBVIRT_NETWORK/g;" "$image_xml_path" > $tmp_xml 2>>$DEBUG_LOG
		virsh --connect qemu:///system define $tmp_xml >>$DEBUG_LOG 2>&1
		if [ ! "$?" -eq '0' ]; then
			printf "$o_err Unable to define virtual machine from $tmp_xml. Check $DEBUG_LOG for more details\n"
			exit 2
		fi

		printf "$o_inf creating disk '$VM_PREFIX$image_name-$vm_number'\n"
		echo "lvcreate" "newvm" "$image_name" "$image_name-$vm_number" | sudo -n $FASTVM_HELPER
		echo "chgrp" "/dev/$THINPOOL_VG/$VM_PREFIX$image_name-$vm_number" | sudo -n $FASTVM_HELPER

		printf "$o_inf adding static lease for 192.168.$SUBNET_NUMBER.$vm_number into libvirts DHCP\n"
		VM_MAC=$(virsh --connect qemu:///system dumpxml "$VM_PREFIX$image_name-$vm_number"|grep 'mac address'|cut -d\' -f 2)
		virsh --connect qemu:///system net-update "$LIBVIRT_NETWORK" add-last ip-dhcp-host --xml "<host mac='$VM_MAC' ip='192.168.$SUBNET_NUMBER.$vm_number'/>" --live --config >>$DEBUG_LOG 2>&1
		vm_mac="$VM_MAC" # temporary transition variable

		# source file with hacks and apply them
		if [ ! -z "$hack_file" ]; then
			printf "$o_inf applying hacks from $hack_file\n"
			. $hack_file
			if [ ! "$?" -eq "0" ]; then
				printf "$o_wrn there was issue applying hacks to this machine, check $DEBUG_LOG for more details\n"
			fi
			printf "$o_inf applying hacks finished\n"
		fi

		printf "$o_ok VM '$VM_NAME' created\n"
		;;

	start)
		vm_number="$2"
		if [ -z "$vm_number" ]; then printf "$o_err VM number missing\n"; usage start; fi
		
		vm_name=$(virsh --connect qemu:///system list --all |grep "$VM_PREFIX"|awk '{print $2}'|egrep "\-$vm_number$")

		if [ -z "$vm_name" ]; then
			printf "$o_err VM with number '$vm_number' not found\n"
			exit 1
		fi
		
		# if there is any third argument start VM and console after
		if [ -z "$3" ]; then
			printf "$o_inf starting VM $vm_name\n"
			virsh --connect qemu:///system start $vm_name >>$DEBUG_LOG 2>&1
			if [ "$?" != '0' ]; then
				printf "$o_err failed to start VM, check $DEBUG_LOG for more information\n"
			fi
		else
			case "$3" in
				console)
					printf "$o_inf starting VM $vm_name and connecting to it serial console ...\n"
					virsh --connect qemu:///system start $vm_name 2>>$DEBUG_LOG
					if [ "$?" != '0' ]; then
						printf "$o_err failed to start VM, check $DEBUG_LOG for more information\n"
					else
						virsh --connect qemu:///system console $vm_name 2>>$DEBUG_LOG
					fi
				;;
				ssh)
					printf "$o_inf starting VM $vm_name\n"
					virsh --connect qemu:///system start $vm_name 2>>$DEBUG_LOG
					if [ "$?" != '0' ]; then
						printf "$o_err failed to start VM, check $DEBUG_LOG for more information\n"
					else
						wait_for_ssh "$vm_number"
						if [ ! -z "$4" ] && [ -x "$4" ]; then
							eval "$4 192.168.$SUBNET_NUMBER.$vm_number"
						else
							ssh -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "root@192.168.$SUBNET_NUMBER.$vm_number"
						fi
					fi
				;;
				*)
					usage start
				;;
			esac
		fi
		;;
	stop)
		vm_number="$2"
		if [ -z "$vm_number" ]; then printf "$o_err VM number missing\n"; usage stop; fi

		vm_name=$(virsh --connect qemu:///system list --all |grep "$VM_PREFIX"|awk '{print $2}'|egrep "\-$vm_number$")
		if [ -z "$vm_name" ]; then
			printf "$o_err VM with number '$vm_number' not found\n"
			exit 1
		fi

		if [ ! -z "$3" ] && [ "$3" = "graceful" ]; then
			printf "$o_inf Sending ACPI shutdown event\n"
			virsh --connect qemu:///system shutdown $vm_name 2>>$DEBUG_LOG
		else
			printf "$o_inf Stopping VM now\n"
			virsh --connect qemu:///system destroy $vm_name 2>>$DEBUG_LOG
		fi
		;;
	ssh)
		vm_number="$2"
		if [ -z "$vm_number" ]; then printf "$o_err VM number missing\n"; usage ssh; fi

		wait_for_ssh "$vm_number"
		if [ ! -z "$3" ] && [ -x "$3" ]; then
			eval "$3 192.168.$SUBNET_NUMBER.$vm_number"
		else
			ssh -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "root@192.168.$SUBNET_NUMBER.$vm_number"
		fi
		;;
	console)
		vm_number="$2"
		if [ -z "$vm_number" ]; then printf "$o_err VM number missing\n"; usage console; fi

		vm_name=$(virsh --connect qemu:///system list --all |grep "$VM_PREFIX"|awk '{print $2}'|egrep "\-$vm_number$")
		if [ -z "$vm_name" ]; then
			printf "$o_err VM with number '$vm_number' not found\n"
			exit 1
		fi

		virsh --connect qemu:///system console $vm_name 2>>$DEBUG_LOG
		;;
	delete)
		vm_number="$2"
		if [ -z "$vm_number" ]; then printf "$o_err VM number missing\n"; usage delete; fi

		vm_name=$(virsh --connect qemu:///system list --all |grep "$VM_PREFIX"|awk '{print $2}'|egrep "\-$vm_number$")
		if [ -z "$vm_name" ]; then
			printf "$o_err VM with number '$vm_number' not found\n"
			exit 1
		fi

		virsh --connect qemu:///system destroy $vm_name >>$DEBUG_LOG 2>&1

		VM_MAC=$(virsh --connect qemu:///system dumpxml "$vm_name"|grep 'mac address'|cut -d\' -f 2)

		printf "$o_inf removing DHCP reservation\n"
		virsh --connect qemu:///system net-update "$LIBVIRT_NETWORK" delete ip-dhcp-host --xml "<host mac='$VM_MAC' ip='192.168.$SUBNET_NUMBER.$vm_number'/>" --live --config >>$DEBUG_LOG 2>&1
		PATH="$PATH:/usr/sbin" which dhcp_release >/dev/null 2>&1
		if [ "$?" -eq '0' ]; then
			echo "dhcp_release" "$LIBVIRT_NETWORK" "$vm_number" "$VM_MAC" | sudo -n $FASTVM_HELPER
		else
			printf "$o_wrn dhcp_release not found, to reuse the same VM number you would need to delete DHCP leases file for $LIBVIRT_NETWORK network and restart this network in the libvirt.\nhttp://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2007q1/001094.html\n"
		fi
		
		printf "$o_inf removing VM drive\n"
		echo "lvremove" "/dev/$THINPOOL_VG/$vm_name" | sudo -n $FASTVM_HELPER

		printf "$o_inf undefining VM from libvirt\n"
		virsh --connect qemu:///system undefine $vm_name >>$DEBUG_LOG 2>&1

		printf "$o_ok VM '$vm_name' deleted\n"
		;;
	list)
		echo "VM#   status     image_name"
		echo "==========================="
		virsh --connect qemu:///system list --all |awk '{print $2,$3,$4,$5}'|egrep "^${VM_PREFIX}.*-[0-9]+"|sed "s/${VM_PREFIX}\(.\+\)-\([0-9]\+\) \([a-zA-Z ]\+\)$/\2 - \3 - \1/" |sort -n
		;;
	*) 
		printf "$o_err unknown action\n"
		usage
		;;
esac	
